# Generated by Django 5.2.8 on 2025-11-28 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buyerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerrequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
